<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$source=dirname(__DIR__);require $source.'/vendor/autoload.php';
$fixture=getenv('CMS_PACKAGE_TEST_ROOT') ?: sys_get_temp_dir().'/favorite-cms-packages-'.bin2hex(random_bytes(6));
if(is_dir($fixture))throw new RuntimeException('Package fixture root must be fresh.');mkdir($fixture,0755,true);
define('APP_ROOT',$fixture);define('APP_VERSION','1.0.2');
$app=new FavoriteCMS\Core\Application();$db=new FavoriteCMS\Core\Database(['driver'=>'sqlite','database'=>':memory:']);$app->instance(FavoriteCMS\Core\Database::class,$db);$db->execute('CREATE TABLE settings (id INTEGER PRIMARY KEY AUTOINCREMENT, group_name TEXT,setting_key TEXT,value TEXT,type TEXT,updated_at TEXT,created_at TEXT,is_public INTEGER)');
$theme=new FavoriteCMS\Themes\ThemeManager($app);$plugin=new FavoriteCMS\Plugins\PluginManager($app);$validator=new FavoriteCMS\Services\Update\UpdatePackageValidator();$results=[];
function testPackage(string $name,callable $run):void{global$results;try{$run();$results[]=['test'=>$name,'status'=>'PASS'];}catch(Throwable$e){$results[]=['test'=>$name,'status'=>'FAIL','error'=>$e->getMessage()];}}
function assertPackage(bool $condition,string $message='Assertion failed'):void{if(!$condition)throw new RuntimeException($message);}
function archiveFixture(string $name,array $files):array{global$fixture;$file=$fixture.'/'.$name.'.zip';$z=new ZipArchive();$z->open($file,ZipArchive::CREATE|ZipArchive::OVERWRITE);foreach($files as$p=>$content)$z->addFromString($p,$content);$z->close();return ['tmp_name'=>$file,'name'=>$name.'.zip','error'=>UPLOAD_ERR_OK];}
function rejects(callable $run,string $contains=''):void{try{$run();}catch(Throwable$e){if($contains!=='')assertPackage(str_contains(strtolower($e->getMessage()),strtolower($contains)),$e->getMessage());return;}throw new RuntimeException('Invalid package was accepted.');}
$themeZip=archiveFixture('theme-valid',['download/theme.json'=>'{"id":"qa-theme","name":"Test Theme","version":"1.0.0"}','download/index.php'=>'<?php echo "Theme";','download/assets/style.css'=>'body{}']);
$pluginZip=archiveFixture('plugin-valid',['repo-release/plugin.json'=>'{"id":"qa-plugin","name":"Test Plugin","version":"1.0.0","entry_point":"src/boot.php"}','repo-release/src/boot.php'=>'<?php // no execution']);
testPackage('plugin ZIP rejected by Themes before any files are written',function()use($theme,$pluginZip){rejects(fn()=>$theme->installFromZip($pluginZip),'plugin ZIP');assertPackage(!is_dir(APP_ROOT.'/themes'));});
testPackage('theme ZIP rejected by Plugins before any files are written',function()use($plugin,$themeZip){rejects(fn()=>$plugin->installFromZip($themeZip),'theme ZIP');assertPackage(!is_dir(APP_ROOT.'/plugins'));});
testPackage('wrapped theme installs under manifest ID with assets',function()use($theme,$themeZip){$r=$theme->installFromZip($themeZip);assertPackage($r['theme_id']==='qa-theme');assertPackage(is_file(APP_ROOT.'/themes/qa-theme/assets/style.css'));});
testPackage('wrapped plugin with different folder name/custom entry installs correctly',function()use($plugin,$pluginZip){$r=$plugin->installFromZip($pluginZip);assertPackage($r['valid']);assertPackage($r['plugin_id']==='qa-plugin');assertPackage(is_file(APP_ROOT.'/plugins/qa-plugin/src/boot.php'));});
testPackage('flat theme and plugin packages keep their entry points and subdirectories',function()use($theme,$plugin){$t=archiveFixture('flat-theme',['theme.json'=>'{"id":"flat-theme"}','index.php'=>'<?php','assets/main.css'=>'/* css */']);$p=archiveFixture('flat-plugin',['plugin.json'=>'{"id":"flat-plugin"}','plugin.php'=>'<?php','assets/main.js'=>'/* js */']);assertPackage($theme->installFromZip($t)['success']);assertPackage($plugin->installFromZip($p)['valid']);});
testPackage('legacy theme without manifest remains installable',function()use($theme){assertPackage($theme->installFromZip(archiveFixture('legacy',['legacy-theme/index.php'=>'<?php','legacy-theme/header.php'=>'<?php']))['theme_id']==='legacy-theme');});
testPackage('dependency compatibility warning does not remove install-now flow',function()use($plugin){$r=$plugin->installFromZip(archiveFixture('dependent',['plugin.json'=>'{"id":"dependent","dependencies":["missing-dependency"]}','plugin.php'=>'<?php']));assertPackage($r['success'] && !$r['valid']);assertPackage(is_file(APP_ROOT.'/plugins/dependent/plugin.php'));});
testPackage('replacement preserves existing extra data and installs new code',function()use($plugin){file_put_contents(APP_ROOT.'/plugins/qa-plugin/user-data.txt','keep');$r=$plugin->installFromZip(archiveFixture('replacement',['whatever/plugin.json'=>'{"id":"qa-plugin","entry_point":"src/boot.php"}','whatever/src/boot.php'=>'<?php // new']));assertPackage($r['valid']);assertPackage(file_get_contents(APP_ROOT.'/plugins/qa-plugin/user-data.txt')==='keep');assertPackage(str_contains(file_get_contents(APP_ROOT.'/plugins/qa-plugin/src/boot.php'),'new'));});
testPackage('invalid replacement leaves previous plugin intact',function()use($plugin){$previous=hash_file('sha256',APP_ROOT.'/plugins/qa-plugin/src/boot.php');rejects(fn()=>$plugin->installFromZip(archiveFixture('broken',['plugin.json'=>'{"id":"qa-plugin"}'])),'missing required');assertPackage(hash_file('sha256',APP_ROOT.'/plugins/qa-plugin/src/boot.php')===$previous);});
testPackage('mixed themes/plugins rejected',function()use($theme,$plugin){$zip=archiveFixture('mixed',['theme.json'=>'{"id":"mixed"}','plugin.json'=>'{"id":"mixed"}','index.php'=>'<?php','plugin.php'=>'<?php']);rejects(fn()=>$theme->installFromZip($zip),'mixed');rejects(fn()=>$plugin->installFromZip($zip),'mixed');});
testPackage('multiple extension roots rejected',function()use($plugin){rejects(fn()=>$plugin->installFromZip(archiveFixture('multi',['a/plugin.json'=>'{"id":"a"}','a/plugin.php'=>'<?php','b/plugin.json'=>'{"id":"b"}','b/plugin.php'=>'<?php'])),'multiple');});
testPackage('invalid manifest and missing template rejected',function()use($theme,$plugin){rejects(fn()=>$theme->installFromZip(archiveFixture('bad-json',['theme.json'=>'{','index.php'=>'<?php'])),'Invalid');rejects(fn()=>$theme->installFromZip(archiveFixture('no-index',['theme.json'=>'{"id":"x"}'])),'missing');rejects(fn()=>$plugin->installFromZip(archiveFixture('no-manifest',['plugin.php'=>'<?php'])),'missing plugin.json');});
testPackage('invalid manifest ID and unsafe entry point rejected',function()use($plugin){rejects(fn()=>$plugin->installFromZip(archiveFixture('bad-id',['plugin.json'=>'{"id":"../escape"}','plugin.php'=>'<?php'])),'Extension ID');rejects(fn()=>$plugin->installFromZip(archiveFixture('bad-entry',['plugin.json'=>'{"id":"escape","entry_point":"../outside.php"}','outside.php'=>'<?php'])),'entry point');});
testPackage('slash/backslash traversal, absolute and drive paths rejected',function()use($plugin,$validator){foreach(['../outside.php','x/../../outside.php','x\\..\\outside.php','/absolute.php','C:\\outside.php']as$path){$zip=archiveFixture('traversal'.bin2hex(random_bytes(3)),['plugin.json'=>'{"id":"traversal"}','plugin.php'=>'<?php',$path=>'bad']);rejects(fn()=>$plugin->installFromZip($zip),'archive path');assertPackage(!$validator->validate($zip['tmp_name'])['valid']);}});
testPackage('case and slash-normalized duplicate entries rejected',function()use($plugin){rejects(fn()=>$plugin->installFromZip(archiveFixture('duplicates',['plugin.json'=>'{"id":"duplicates"}','plugin.php'=>'<?php','assets\\a.js'=>'1','assets/a.js'=>'2'])),'Duplicate');rejects(fn()=>$plugin->installFromZip(archiveFixture('case-duplicate',['plugin.json'=>'{"id":"duplicate"}','plugin.php'=>'<?php','Asset.js'=>'1','asset.js'=>'2'])),'Duplicate');});
testPackage('ZIP symlink rejected',function()use($plugin){$file=archiveFixture('symlink',['plugin.json'=>'{"id":"symlink"}','plugin.php'=>'<?php','link'=>'../../outside']);$z=new ZipArchive();$z->open($file['tmp_name']);$z->setExternalAttributesName('link',3,0120777<<16);$z->close();rejects(fn()=>$plugin->installFromZip($file),'symlinks');});
testPackage('Windows archive paths install canonically without backslash filenames',function()use($plugin){$r=$plugin->installFromZip(archiveFixture('windows',['wrapped\\plugin.json'=>'{"id":"windows-plugin"}','wrapped\\plugin.php'=>'<?php','wrapped\\assets\\a.css'=>'/* css */']));assertPackage($r['valid']);assertPackage(is_file(APP_ROOT.'/plugins/windows-plugin/assets/a.css'));});
$core=['bootstrap.php'=>"<?php define('APP_VERSION','1.1.0');",'index.php'=>'<?php','migrate.php'=>'<?php','app/Core/Application.php'=>'<?php','public/index.php'=>'<?php','release.json'=>'{"product":"Favorite CMS Universal","version":"1.1.0"}'];
testPackage('Core validator accepts flat and wrapper releases and Windows names',function()use($core,$validator){foreach(['','release/','windows\\']as$prefix){$files=[];foreach($core as$p=>$value)$files[$prefix.($prefix==='windows\\'?str_replace('/','\\',$p):$p)]=$value;$z=archiveFixture('core-'.bin2hex(random_bytes(2)),$files);$r=$validator->validate($z['tmp_name']);assertPackage($r['valid'],implode(';',$r['errors']));assertPackage($r['version']==='1.1.0');}});
testPackage('Core ZIP rejected by both extension uploaders',function()use($core,$theme,$plugin){$zip=archiveFixture('core',$core);rejects(fn()=>$theme->installFromZip($zip),'Core');rejects(fn()=>$plugin->installFromZip($zip),'plugin.json');});
testPackage('Core identity/version/file and private-data checks remain enforced',function()use($core,$validator){$missing=$core;unset($missing['migrate.php']);assertPackage(!$validator->validate(archiveFixture('core-missing',$missing)['tmp_name'])['valid']);$private=$core;$private['.env']='secret';assertPackage(!$validator->validate(archiveFixture('core-private',$private)['tmp_name'])['valid']);$dev=$core;$dev['tests/test.php']='<?php';assertPackage(!$validator->validate(archiveFixture('core-dev',$dev)['tmp_name'])['valid']);assertPackage(!$validator->validate(archiveFixture('not-core',['plugin.json'=>'{}','plugin.php'=>'<?php'])['tmp_name'])['valid']);});
testPackage('canonical extractor handles Windows Core paths',function()use($core){$files=[];foreach($core as$p=>$v)$files['wrapper\\'.str_replace('/','\\',$p)]=$v;$zip=archiveFixture('extract-core',$files);$z=new ZipArchive();$z->open($zip['tmp_name']);FavoriteCMS\Services\ZipPackage::extract($z,APP_ROOT.'/core-staging',FavoriteCMS\Services\ZipPackage::entries($z));$z->close();assertPackage(is_file(APP_ROOT.'/core-staging/wrapper/bootstrap.php'));assertPackage(is_file(APP_ROOT.'/core-staging/wrapper/app/Core/Application.php'));});
foreach($results as$r)echo json_encode($r).PHP_EOL;
file_put_contents(APP_ROOT.'/package-results.json',json_encode($results,JSON_PRETTY_PRINT));echo 'Fixture: '.APP_ROOT.PHP_EOL;
$failed=count(array_filter($results,static fn($r)=>$r['status']==='FAIL'));echo count($results).' package checks; '.$failed.' failures.'.PHP_EOL;exit($failed?1:0);