<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
define('CMS_RENDER_FIXTURE_ONLY', true); require __DIR__.'/render.php';
use FavoriteCMS\Services\{SeoMetadata,SeoTransfer,SeoSitemap,SeoAudit,FrontendSeoService,SeoRedirects};
use FavoriteCMS\Models\{Post,Page,Setting};
use FavoriteCMS\Core\{Request,Kernel};
if(getenv('CMS_SEO_MYSQL')==='1') {
 $port=getenv('CMS_TEST_DB_PORT');if(!$port)throw new RuntimeException('Specify the disposable local MySQL test port.');
 $config=['driver'=>'mysql','host'=>'127.0.0.1','port'=>$port,'username'=>getenv('CMS_TEST_DB_USER')?:'root','password'=>getenv('CMS_TEST_DB_PASSWORD')?:'','charset'=>'utf8mb4','prefix'=>'seotest_'];
 $server=new PDO('mysql:host=127.0.0.1;port='.$port,$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$config['database']='favorite_seo_qa_'.bin2hex(random_bytes(6));$server->exec('CREATE DATABASE `'.$config['database'].'` CHARACTER SET utf8mb4');
 $db=new FavoriteCMS\Core\Database($config);$app->instance(FavoriteCMS\Core\Database::class,$db);
 foreach(glob(APP_ROOT.'/database/migrations/*.php')as$file){require_once$file;preg_match('/class\s+([A-Za-z0-9_]+)/',file_get_contents($file),$match);$class=$match[1];(new $class($db))->up();}
 $uid=$db->insert('users',['username'=>'seo-test-admin','email'=>'seo@example.test','name'=>'SEO Test Admin','password'=>'test-only','status'=>'active','email_verified_at'=>'2026-10-07 00:00:00']);$role=$db->selectOne("SELECT id FROM `roles` WHERE slug='super-admin'");$db->insert('user_roles',['user_id'=>$uid,'role_id'=>$role->id]);$_SESSION['auth_user_id']=$uid;
}
$results=[];
function seoCheck(string $name,callable $run):void {global $results;try{$run();$results[]=['test'=>$name,'status'=>'PASS'];}catch(Throwable $e){$results[]=['test'=>$name,'status'=>'FAIL','error'=>$e->getMessage()];}}
function seoAssert(bool $ok,string $message='Assertion failed'):void {if(!$ok)throw new RuntimeException($message);}
function seoDom(string $html):DOMXPath {$doc=new DOMDocument();$old=libxml_use_internal_errors(true);$doc->loadHTML('<?xml encoding="UTF-8">'.$html);libxml_clear_errors();libxml_use_internal_errors($old);return new DOMXPath($doc);}
Setting::set('general','site_url','https://example.test/cms');Setting::set('general','site_name','Example Site');Setting::set('seo','title_separator','|');
$post=Post::create(['author_id'=>$uid,'title'=>'বাংলা তথ্য ও ব্যবহার','slug'=>'seo-bangla','content'=>'<script>alert("secret")</script><style>.secret{}</style><p>বাংলা লেখার একটি পরিষ্কার বিবরণ। এখানে ব্যবহারকারীর প্রয়োজনীয় তথ্য দেওয়া আছে।</p>','status'=>'published','type'=>'post']);
$page=Page::create(['author_id'=>$uid,'title'=>'Useful page','slug'=>'seo-page','content'=>'<p>A useful page-specific description instead of the global default.</p>','status'=>'published']);
seoCheck('automatic metadata uses readable Bengali and never saves generated fields',function()use($post){$before=$post->getSeoMeta();$meta=SeoMetadata::resolve(['post'=>$post]);seoAssert(str_contains($meta['title'],'বাংলা'));seoAssert(str_contains($meta['description'],'বাংলা লেখার'));seoAssert(!str_contains($meta['description'],'secret'));seoAssert($before===$post->getSeoMeta());});
seoCheck('excerpt takes precedence over content when metadata is empty',function()use($post){$post->excerpt='A chosen excerpt';seoAssert(SeoMetadata::resolve(['post'=>$post])['description']==='A chosen excerpt');unset($post->excerpt);});
seoCheck('summary removes markup, scripts, shortcodes and preserves word boundaries',function(){seoAssert(SeoMetadata::text('<p>A &amp; B</p><script>bad</script>[gallery id="1"]<p>C</p>',true)==='A & B C');$summary=SeoMetadata::summary(str_repeat('বাংলা শব্দ ',40));seoAssert(mb_check_encoding($summary,'UTF-8'));seoAssert(str_ends_with($summary,'…'));seoAssert(!str_contains($summary,'<'));});
seoCheck('curated search fields and independent social fields are preserved',function()use($post){SeoTransfer::write($post,['meta_title'=>'Search title','meta_description'=>'Search description','og_title'=>'Share title','og_description'=>'Share description'],true);$meta=SeoMetadata::resolve(['post'=>$post]);seoAssert($meta['title']==='Search title'&&$meta['og_title']==='Share title');$head=FrontendSeoService::renderHeadTags(['post'=>$post]);$xp=seoDom($head);seoAssert($xp->evaluate('string(//meta[@property="og:title"]/@content)')==='Share title');seoAssert(str_contains($head,'বাংলা তথ্য'));});
seoCheck('automatic fallback follows content edits while curated metadata remains unchanged',function()use($page,$post){$page->update(['content'=>'<p>New page summary.</p>']);seoAssert(SeoMetadata::resolve(['page'=>Page::find($page->id)])['description']==='New page summary.');$post->update(['content'=>'<p>New content</p>']);seoAssert(SeoMetadata::resolve(['post'=>Post::find($post->id)])['description']==='Search description');});
seoCheck('default theme renders exactly one consistent search title and description',function()use($app,$page){$html=(new FavoriteCMS\Rendering\Engine($app))->render('page',['page'=>Page::find($page->id)]);$xp=seoDom($html);seoAssert($xp->query('//title')->length===1);seoAssert($xp->query('//meta[@name="description"]')->length===1);seoAssert($xp->evaluate('string(//meta[@name="description"]/@content)')==='New page summary.');});
seoCheck('core fallback receives search metadata and schema without duplicate tags',function()use($app,$page){$engine=new FavoriteCMS\Rendering\Engine($app);$engine->setActiveTheme('missing-seo-theme');$xp=seoDom($engine->render('page',['page'=>Page::find($page->id)]));seoAssert($xp->query('//title')->length===1);seoAssert($xp->query('//meta[@name="description"]')->length===1);seoAssert($xp->query('//script[@type="application/ld+json"]')->length===1);});
seoCheck('first content image supplies a social fallback without changing content',function()use($page){$page->content='<p>Text</p><img src="/images/first.jpg">';$head=FrontendSeoService::renderHeadTags(['page'=>$page]);seoAssert(seoDom($head)->evaluate('string(//meta[@property="og:image"]/@content)')==='https://example.test/cms/images/first.jpg');});
seoCheck('social image override is validated and takes precedence',function()use($post){SeoTransfer::write($post,['og_image_url'=>'https://images.example.test/social.jpg'],true);$head=FrontendSeoService::renderHeadTags(['post'=>$post]);seoAssert(seoDom($head)->evaluate('string(//meta[@property="og:image"]/@content)')==='https://images.example.test/social.jpg');try{SeoTransfer::clean(['og_image_url'=>'javascript:alert(1)']);throw new RuntimeException('Unsafe URL accepted');}catch(InvalidArgumentException){}});
seoCheck('CSV with quoted commas and UTF-8, and JSON row lists parse correctly',function()use($post){$rows=SeoTransfer::parse("\xEF\xBB\xBFobject_type,id,meta_description\npost,".$post->id.",\"বাংলা, পরিষ্কার বিবরণ\"\n",'csv');seoAssert(count($rows)===1&&str_contains($rows[0]['meta_description'],'বাংলা,'));seoAssert(count(SeoTransfer::parse(json_encode($rows),'json'))===1);});
seoCheck('fill-only preview skips existing values but accepts empty metadata',function()use($post,$page){$preview=SeoTransfer::preview([['object_type'=>'post','id'=>$post->id,'meta_title'=>'Changed'],['object_type'=>'page','id'=>$page->id,'meta_title'=>'New title']]);seoAssert(!$preview['errors']);seoAssert(!$preview['plan'][0]['changes']);seoAssert(isset($preview['plan'][1]['changes']['meta_title']));seoAssert(SeoTransfer::apply($preview)===1);seoAssert($post->getSeoMeta()->meta_title==='Search title');});
seoCheck('explicit overwrite applies reviewed fields and never changes content/status',function()use($page){$before=Page::find($page->id)->toArray();$preview=SeoTransfer::preview([['object_type'=>'page','id'=>$page->id,'meta_title'=>'Reviewed replacement']],true);seoAssert(SeoTransfer::apply($preview)===1);seoAssert(Page::find($page->id)->toArray()===$before);});
seoCheck('blank imported fields retain curated values and noindex',function()use($page){SeoTransfer::write($page,['robots'=>'noindex,follow'],true);$preview=SeoTransfer::preview([['object_type'=>'page','id'=>$page->id,'meta_title'=>'','robots'=>'']],true);seoAssert(!$preview['plan'][0]['changes']);seoAssert(SeoTransfer::apply($preview)===0);seoAssert($page->getSeoMeta()->robots==='noindex,follow');});
seoCheck('conflicting identifiers, wrong types, foreign URLs and duplicate targets are rejected',function()use($post,$page){foreach([[['object_type'=>'post','id'=>$post->id,'slug'=>'missing']],[['object_type'=>'theme','id'=>1]],[['object_type'=>'post','url'=>'https://foreign.test/post/seo-bangla']],[['object_type'=>'post','id'=>$post->id],['object_type'=>'post','id'=>$post->id]]]as$rows)seoAssert((bool)SeoTransfer::preview($rows)['errors']);});
seoCheck('same-site subdirectory URL resolves the intended content',function()use($post){$preview=SeoTransfer::preview([['object_type'=>'post','url'=>'https://example.test/cms/post/seo-bangla','meta_description'=>'Matched URL']],true);seoAssert(!$preview['errors']&&$preview['plan'][0]['id']===(int)$post->id);});
seoCheck('unsafe canonical, unknown robots, nested values and duplicate CSV headers fail',function(){foreach([['canonical_url'=>'javascript:bad'],['robots'=>'index,evil'],['meta_title'=>['bad']]]as$row){try{SeoTransfer::clean($row);throw new RuntimeException('Invalid row accepted');}catch(InvalidArgumentException){}}try{SeoTransfer::parse("object_type,id,id\npost,1,1",'csv');throw new RuntimeException('Duplicate header accepted');}catch(InvalidArgumentException){}});
seoCheck('stale preview rolls back all previously applied rows',function()use($post,$page){$before=$post->getSeoMeta()->meta_title;$preview=SeoTransfer::preview([['object_type'=>'post','id'=>$post->id,'meta_title'=>'Rollback this'],['object_type'=>'page','id'=>$page->id,'meta_title'=>'Stale']],true);SeoTransfer::write($page,['meta_title'=>'Concurrent edit'],true);try{SeoTransfer::apply($preview);throw new RuntimeException('Stale preview accepted');}catch(RuntimeException $e){seoAssert(str_contains($e->getMessage(),'changed'));}seoAssert($post->getSeoMeta()->meta_title===$before);});
seoCheck('CSV exports explicit fields and neutralizes spreadsheet formulas',function()use($post){SeoTransfer::write($post,['meta_title'=>'=HYPERLINK("https://example.test")'],true);$csv=SeoTransfer::csv([$post]);seoAssert(str_contains($csv,"'=HYPERLINK"));$rows=SeoTransfer::parse($csv,'csv');seoAssert($rows[0]['id']==$post->id);SeoTransfer::write($post,['meta_title'=>'Search title'],true);});
seoCheck('slug redirects follow current destination directly and do not loop',function()use($post){$post->update(['slug'=>'seo-next']);$fresh=Post::find($post->id);$fresh->update(['slug'=>'seo-final']);$response=SeoRedirects::resolve('post','seo-bangla');seoAssert($response?->getStatus()===301);$headers=(new ReflectionProperty($response,'headers'))->getValue($response);seoAssert(str_ends_with($headers['Location'],'/post/seo-final'));seoAssert(SeoRedirects::resolve('post','seo-final')===null);});
seoCheck('unpublished/deleted redirect targets remain unavailable',function()use($post){Post::find($post->id)->update(['status'=>'draft']);seoAssert(SeoRedirects::resolve('post','seo-bangla')===null);Post::find($post->id)->update(['status'=>'published']);});
seoCheck('existing live slug takes precedence over an old redirect',function()use($app,$post,$uid){Post::create(['author_id'=>$uid,'title'=>'Reused slug','slug'=>'seo-bangla','content'=>'<p>New owner</p>','status'=>'published','type'=>'post']);$response=(new FavoriteCMS\Http\Controllers\FrontendController($app))->post(Request::create('GET','/post/seo-bangla'),'seo-bangla');seoAssert($response->getStatus()===200&&str_contains($response->getContent(),'Reused slug'));});
seoCheck('page slug changes also generate published-only redirects',function()use($page){$page->update(['slug'=>'page-next']);seoAssert(SeoRedirects::resolve('page','seo-page')?->getStatus()===301);});
seoCheck('audit finds missing alt text, broken content links and duplicate titles',function()use($db,$uid){$a=Post::create(['author_id'=>$uid,'title'=>'Duplicate title','slug'=>'duplicate-a','content'=>'<img src="/x.jpg"><a href="/post/missing">Missing</a>','status'=>'published','type'=>'post']);Post::create(['author_id'=>$uid,'title'=>'Duplicate title','slug'=>'duplicate-b','content'=>'<p>Other</p>','status'=>'published','type'=>'post']);$issues=implode(';',SeoAudit::issues($a));seoAssert(str_contains($issues,'Duplicate'));seoAssert(str_contains($issues,'alt'));seoAssert(str_contains($issues,'Broken'));});
seoCheck('sitemap index covers over 1000 posts with no repeats or drafts/noindex/external canonical',function()use($db,$uid,$page){for($i=1;$i<=1005;$i++)$db->insert('posts',['author_id'=>$uid,'title'=>'Bulk '.$i,'slug'=>'bulk-'.$i,'content'=>'<p>Bulk</p>','status'=>'published','type'=>'post']);$excluded=Post::create(['author_id'=>$uid,'title'=>'Excluded','slug'=>'excluded-noindex','content'=>'<p>Hidden</p>','status'=>'published','type'=>'post']);SeoTransfer::write($excluded,['robots'=>'noindex,follow']);$canonical=Post::create(['author_id'=>$uid,'title'=>'Canonical elsewhere','slug'=>'canonical-elsewhere','content'=>'<p>Other</p>','status'=>'published','type'=>'post']);SeoTransfer::write($canonical,['canonical_url'=>'https://other.example.test/article']);$request=Request::create('GET','/sitemap.xml');$index=simplexml_load_string(SeoSitemap::render($request)->getContent());seoAssert($index->getName()==='sitemapindex');$urls=[];foreach($index->sitemap as$entry){preg_match('/sitemap-(\d+)\.xml/',(string)$entry->loc,$m);$chunk=simplexml_load_string(SeoSitemap::render($request,(int)$m[1])->getContent());foreach($chunk->url as$url)$urls[]=(string)$url->loc;}seoAssert(count(array_unique($urls))===count($urls));seoAssert(in_array('https://example.test/cms/post/bulk-1005',$urls,true));seoAssert(!in_array('https://example.test/cms/post/excluded-noindex',$urls,true));seoAssert(!in_array('https://example.test/cms/post/canonical-elsewhere',$urls,true));seoAssert(!in_array('https://example.test/cms/page/page-next',$urls,true));seoAssert(SeoSitemap::render($request,999)->getStatus()===404);});
seoCheck('new migration is idempotent',function()use($db){(new CreateSeoAutomation($db))->up();seoAssert($db->tableExists('seo_redirects'));});
seoCheck('JSON content adapters retain post/page metadata for migration',function(){ $adapter=new FavoriteCMS\Services\Import\Adapters\JsonAdapter();$data=$adapter->parse(json_encode(['posts'=>[['id'=>1,'title'=>'P','content'=>'Text','seo'=>['meta_title'=>'Imported SEO']]],'pages'=>[['id'=>2,'title'=>'Page','meta_description'=>'Imported page description']]]));seoAssert($data->posts[0]->metadata['seo']['meta_title']==='Imported SEO');seoAssert($data->pages[0]->metadata['seo']['meta_description']==='Imported page description');});
seoCheck('schema remains valid JSON with website/publisher identities and content headline',function()use($post){$head=FrontendSeoService::renderHeadTags(['post'=>Post::find($post->id)]);$xp=seoDom($head);$schema=json_decode($xp->evaluate('string(//script[@type="application/ld+json"])'),true,512,JSON_THROW_ON_ERROR);$types=array_column($schema['@graph'],'@type');seoAssert(in_array('WebSite',$types,true)&&in_array('Organization',$types,true)&&in_array('Article',$types,true));});
seoCheck('local URLs already containing the installation subdirectory are not doubled',function(){seoAssert(SeoMetadata::httpUrl('/cms/uploads/sample.jpg')==='https://example.test/cms/uploads/sample.jpg');seoAssert(SeoMetadata::httpUrl('https://user:secret@example.test/a')==='');});
seoCheck('unclosed scripts never become an automatic description',function(){seoAssert(SeoMetadata::text('<p>Safe text</p><script>secret never closed')==='Safe text');});
seoCheck('WordPress SEO after thumbnail metadata is retained, including noindex',function(){
 $xml='<rss xmlns:wp="http://wordpress.org/export/1.2/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/"><channel><wp:wxr_version>1.2</wp:wxr_version><item><title>WP article</title><guid>wp-seo</guid><wp:post_id>42</wp:post_id><wp:post_type>post</wp:post_type><wp:status>publish</wp:status><wp:post_name>wp-article</wp:post_name><content:encoded><![CDATA[<p>WP body</p>]]></content:encoded><wp:postmeta><wp:meta_key>_thumbnail_id</wp:meta_key><wp:meta_value>99</wp:meta_value></wp:postmeta><wp:postmeta><wp:meta_key>_yoast_wpseo_title</wp:meta_key><wp:meta_value>WP search title</wp:meta_value></wp:postmeta><wp:postmeta><wp:meta_key>_yoast_wpseo_meta-robots-noindex</wp:meta_key><wp:meta_value>1</wp:meta_value></wp:postmeta></item></channel></rss>';
 $parsed=(new FavoriteCMS\Services\Import\Adapters\WordPressAdapter())->parse($xml);seoAssert($parsed->posts[0]->metadata['seo']['meta_title']==='WP search title');seoAssert($parsed->posts[0]->metadata['seo']['robots']==='noindex,follow');
});
seoCheck('actual JSON content import saves post/page SEO with the original import flow',function()use($app,$uid){$engine=new FavoriteCMS\Services\Import\ImportEngine($app);$payload=json_encode(['posts'=>[['id'=>'seo-import-p','title'=>'Imported post SEO','slug'=>'import-post-seo','content'=>'<p>Imported post body</p>','status'=>'published','seo'=>['meta_title'=>'Imported custom search']]],'pages'=>[['id'=>'seo-import-page','title'=>'Imported page SEO','slug'=>'import-page-seo','content'=>'<p>Imported page body</p>','status'=>'published','meta_description'=>'Imported page metadata']]]);$report=$engine->import($payload,['author_id'=>$uid,'import_media'=>false],'json');seoAssert($report['posts']['imported']===1&&$report['pages']['imported']===1,json_encode($report));seoAssert(Post::findBySlug('import-post-seo')->getSeoMeta()->meta_title==='Imported custom search');seoAssert(Page::findBySlug('import-page-seo')->getSeoMeta()->meta_description==='Imported page metadata');});
seoCheck('search results automatically render noindex while normal pages remain indexable',function()use($app){$html=(new FavoriteCMS\Http\Controllers\FrontendController($app))->search(Request::create('GET','/search?q=bulk'))->getContent();seoAssert(seoDom($html)->evaluate('string(//meta[@name="robots"]/@content)')==='noindex,follow');});
seoCheck('max-image-preview:none does not accidentally exclude an indexable URL',function()use($uid){$item=Post::create(['author_id'=>$uid,'title'=>'Image preview setting','slug'=>'image-preview-none','content'=>'Text','status'=>'published','type'=>'post']);SeoTransfer::write($item,['robots'=>'index,follow,max-image-preview:none']);$request=Request::create('GET','/sitemap.xml');$xml=SeoSitemap::render($request,1)->getContent().SeoSitemap::render($request,2)->getContent();seoAssert(str_contains($xml,'/post/image-preview-none'));});
seoCheck('curated bracketed titles and descriptions remain literal',function()use($post){SeoTransfer::write($post,['meta_title'=>'[Review] A title','meta_description'=>'[Details] A description'],true);$meta=SeoMetadata::resolve(['post'=>$post]);seoAssert($meta['title']==='[Review] A title');seoAssert($meta['description']==='[Details] A description');});
foreach($results as$result)echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).PHP_EOL;
$report=getenv('CMS_SEO_TEST_REPORT')?:__DIR__.'/seo-results.json';file_put_contents($report,json_encode($results,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE));$failed=count(array_filter($results,static fn($row)=>$row['status']==='FAIL'));echo count($results).' SEO checks; '.$failed.' failures.'.PHP_EOL;exit($failed?1:0);